#ifndef APOLLO_CONFIG_H
#define APOLLO_CONFIG_H

#define APOLLO_VERSION_MAJOR 1
#define APOLLO_VERSION_MINOR 0
#define APOLLO_VERSION_PATCH 0
#define APOLLO_VERSION_STRING "1.0.0"

#define APOLLO_ARCH_X86_64 1
#define APOLLO_ARCH_STRING "x86_64"

#define APOLLO_PAGE_SIZE 4096
#define APOLLO_KERNEL_HEAP_SIZE (16 * 1024 * 1024)  // 16MB
#define APOLLO_KERNEL_STACK_SIZE (64 * 1024)        // 64KB
#define APOLLO_MEMORY_ALIGNMENT 8

#define APOLLO_VGA_WIDTH 80
#define APOLLO_VGA_HEIGHT 25
#define APOLLO_VGA_COLORS 16

#define APOLLO_KEYBOARD_BUFFER_SIZE 256
#define APOLLO_COMMAND_MAX_LENGTH 256
#define APOLLO_COMMAND_HISTORY_SIZE 32
#define APOLLO_MAX_COMMAND_ARGS 16

#define APOLLO_MULTIBOOT2_MAGIC 0xe85250d6
#define APOLLO_KERNEL_LOAD_ADDRESS 0x100000  // 1MB

#ifdef DEBUG
    #define APOLLO_DEBUG_ENABLED 1
    #define APOLLO_SERIAL_DEBUG 1
#else
    #define APOLLO_DEBUG_ENABLED 0
    #define APOLLO_SERIAL_DEBUG 0
#endif

#define APOLLO_FEATURE_MEMORY_MANAGER 1
#define APOLLO_FEATURE_COMMAND_SHELL 1
#define APOLLO_FEATURE_VGA_GRAPHICS 1
#define APOLLO_FEATURE_PS2_KEYBOARD 1
#define APOLLO_FEATURE_RTC_CLOCK 1

#define APOLLO_COMPILER_NAME "GCC"
#define APOLLO_BUILD_DATE __DATE__
#define APOLLO_BUILD_TIME __TIME__

#define APOLLO_MAX_FILENAME_LENGTH 255
#define APOLLO_MAX_PATH_LENGTH 1024
#define APOLLO_MAX_PROCESSES 32
#define APOLLO_MAX_THREADS 128

#define APOLLO_ASSERT_ENABLED 1
#define APOLLO_ERROR_CHECKING 1

#define APOLLO_CPU_VENDOR_INTEL 0x756e6547  // "Genu"
#define APOLLO_CPU_VENDOR_AMD   0x68747541  // "Auth"

#define APOLLO_TIMER_FREQUENCY 1000  // 1000 Hz
#define APOLLO_SCHEDULER_QUANTUM 10  // 10ms

#define APOLLO_VGA_CTRL_PORT 0x3D4
#define APOLLO_VGA_DATA_PORT 0x3D5
#define APOLLO_KB_DATA_PORT 0x60
#define APOLLO_KB_STATUS_PORT 0x64
#define APOLLO_CMOS_ADDRESS_PORT 0x70
#define APOLLO_CMOS_DATA_PORT 0x71

#define APOLLO_HEAP_MAGIC 0xDEADBEEF
#define APOLLO_STACK_MAGIC 0xCAFEBABE
#define APOLLO_KERNEL_MAGIC 0x41504F4C  // "APOL"

#define APOLLO_DEFAULT_FG_COLOR 7   // Light gray
#define APOLLO_DEFAULT_BG_COLOR 0   // Black
#define APOLLO_LOGO_COLOR 14        // Yellow
#define APOLLO_ACCENT_COLOR 3       // Orange

#define APOLLO_KB(x) ((x) * 1024)
#define APOLLO_MB(x) ((x) * 1024 * 1024)
#define APOLLO_GB(x) ((x) * 1024ULL * 1024 * 1024)

#define APOLLO_STRINGIFY(x) #x
#define APOLLO_TOSTRING(x) APOLLO_STRINGIFY(x)

#if APOLLO_DEBUG_ENABLED
    #define APOLLO_DEBUG_PRINT(fmt, ...) debug_printf(fmt, ##__VA_ARGS__)
#else
    #define APOLLO_DEBUG_PRINT(fmt, ...) do {} while(0)
#endif

#define APOLLO_STATIC_ASSERT(cond, msg) \
    typedef char apollo_static_assert_##msg[(cond) ? 1 : -1]

APOLLO_STATIC_ASSERT(APOLLO_PAGE_SIZE == 4096, page_size_must_be_4k);
APOLLO_STATIC_ASSERT(APOLLO_MEMORY_ALIGNMENT >= 8, alignment_must_be_at_least_8);
APOLLO_STATIC_ASSERT(APOLLO_KEYBOARD_BUFFER_SIZE > 0, keyboard_buffer_must_be_positive);

#endif